### ISSUE TITLE
Use forked repo for goldfish/ranchu device

### ISSUE THREAD

**Issue by lissyx** [kaiostech/manifests#4]
Gecko requires v1.2 of ISupplicant: https://bugzilla.mozilla.org/show_bug.cgi?id=1638785 this is dealt with in device's manifest, which is part of the device repo.

We need to fork https://android.googlesource.com/device/generic/goldfish/+/refs/tags/android-10.0.0_r11 as `device_generic_goldfish`

**Comment by lissyx** [comment]
https://github.com/kaiostech/manifests/pull/5

**Comment by lissyx** [comment]
And once we have the fork, we can do that PR: https://github.com/lissyx/device_generic_goldfish/pull/1

**Comment by seinlin** [comment]
The related repository is ready and PR is merged.
